# Generated by Django 4.0.6 on 2022-07-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('y_n', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=6)),
                ('providers', models.CharField(choices=[('adobe', 'Adobe'), ('liveramp', 'LiveRamp'), ('neustar', 'Neustar'), ('oracle blue kai', 'Oracle Blue Kai'), ('salesforce (krux)', 'Salesforce (Krux)'), ('none of the above', 'None of the Above')], max_length=50)),
            ],
        ),
    ]
